version: '3'

services:
  db:
    image: kartoza/postgis:10.0-2.4
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: on-failure
volumes:
  pg_data:
    driver: local
