version: '3'

services:
  blood_donor:
    build: .
    command: python models_donor/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: .env
    ports:
      - "8085:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: on-failure
  db:
    restart: always
    image: postgres:11
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
