# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-02-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=18, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=18, verbose_name='longitude')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
