# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2022-02-05 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('blood_type', models.CharField(choices=[('o-', 'O-'), ('o+', 'O+'), ('a-', 'A-'), ('a+', 'A+'), ('b-', 'B-'), ('b+', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB-')], default='o-', max_length=3, verbose_name='blood type')),
                ('blood_unit_type', models.CharField(choices=[('platelets', 'Platelets'), ('plasma', 'Plasma'), ('cryoprecipitate', 'Cryoprecipitate'), ('blood cells', 'Blood cells')], default='blood cells', max_length=15, verbose_name='blood unit type')),
                ('min_qty', models.PositiveIntegerField(verbose_name='minimum quantity')),
                ('max_qty', models.PositiveIntegerField(verbose_name='maximum quantity')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_units', to='blood_center.Center', verbose_name='capacity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
