# Generated by Django 3.2 on 2022-03-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0003_alter_centercapacity_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('prepared', 'Prepared'), ('sending', 'Sending'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('verifying', 'Verifying'), ('finished', 'Finished')], default='created', max_length=25, verbose_name='status')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('type_deadline', models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'High priority'), (5, 'Max')], default=1, max_length=25, verbose_name='type deadline')),
                ('name', models.CharField(max_length=450, verbose_name='name')),
                ('comment', models.CharField(blank=True, max_length=1500, null=True, verbose_name='comment')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='blood_center.center', verbose_name='destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='blood_center.center', verbose_name='origin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='centercapacity',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='centercapacity',
            name='blood_unit_type',
        ),
        migrations.AddField(
            model_name='centercapacity',
            name='type',
            field=models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='blood unit type'),
        ),
        migrations.AlterField(
            model_name='centercapacity',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capabilities', to='blood_center.center', verbose_name='center'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='type')),
                ('blood_type', models.CharField(choices=[('o-', 'O-'), ('o+', 'O+'), ('a-', 'A-'), ('a+', 'A+'), ('b-', 'B-'), ('b+', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB-')], default='o+', max_length=4, verbose_name='blood type')),
                ('expired_at', models.DateTimeField(verbose_name='expired at')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('is_expired', models.BooleanField(default=False, verbose_name='is expired')),
                ('can_transfer', models.BooleanField(default=True, verbose_name='can transfer')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='blood_center.center', verbose_name='center')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CenterTransferUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='blood_center.centertransfer', verbose_name='transfer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='blood_center.unit', verbose_name='unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
