# Generated by Django 3.2 on 2022-03-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0004_auto_20220328_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=18, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=18, verbose_name='longitude'),
        ),
    ]
