# Generated by Django 3.2 on 2022-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0006_unit_is_altruist_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='centertransfer',
            name='receptor_blood_type',
            field=models.CharField(choices=[('o-', 'O-'), ('o+', 'O+'), ('a-', 'A-'), ('a+', 'A+'), ('b-', 'B-'), ('b+', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB-')], default='o+', max_length=4, verbose_name='receptor blood type'),
        ),
        migrations.AddField(
            model_name='centertransfer',
            name='unit_type',
            field=models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='unit type'),
        ),
    ]
