# Generated by Django 3.2 on 2022-04-09 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0007_auto_20220402_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='type',
            field=models.CharField(choices=[('imss', 'IMSS'), ('issste', 'ISSSTE'), ('cnts', 'CNTS (Centro Nacional de la Transfusión Sanguínea)'), ('cets', 'CETS (Centro Estatal de la Transfusión Sanguínea)'), ('ccinshae', 'CCINSHAE (Comisión Coordinadora de Institutos Nacionales de Salud y Hospitales de Alta Especialidad)'), ('dif', 'DIF'), ('pemex', 'PEMEX'), ('sedena', 'SEDENA'), ('semar', 'SEMAR'), ('privados', 'PRIVADOS'), ('universitarios', 'UNIVERSITARIOS'), ('cruz_roja', 'CRUZ_ROJA')], default='imss', max_length=150, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='unit',
            name='donor_age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='donor age'),
        ),
        migrations.AddField(
            model_name='unit',
            name='donor_gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='m', max_length=10, verbose_name='donor gender'),
        ),
    ]
