# Generated by Django 3.2 on 2022-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0008_auto_20220409_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='centertransfer',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
    ]
