# Generated by Django 3.2 on 2022-04-09 14:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_center', '0010_alter_centertransfer_type_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUnit',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='type')),
                ('blood_type', models.CharField(choices=[('o-', 'O-'), ('o+', 'O+'), ('a-', 'A-'), ('a+', 'A+'), ('b-', 'B-'), ('b+', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB-')], default='o+', max_length=4, verbose_name='blood type')),
                ('expired_at', models.DateTimeField(verbose_name='expired at')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('is_expired', models.BooleanField(default=False, verbose_name='is expired')),
                ('can_transfer', models.BooleanField(default=True, verbose_name='can transfer')),
                ('is_altruist_unit', models.BooleanField(default=False, verbose_name='is altruist unit')),
                ('donor_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='m', max_length=10, verbose_name='donor gender')),
                ('donor_age', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='donor age')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blood_center.center', verbose_name='center')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical unit',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCenterTransferUnit',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blood_center.centertransfer', verbose_name='transfer')),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blood_center.unit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'historical center transfer unit',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCenterTransfer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('prepared', 'Prepared'), ('sending', 'Sending'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('verifying', 'Verifying'), ('finished', 'Finished')], default='created', max_length=25, verbose_name='status')),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('type_deadline', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'High priority'), ('5', 'Max')], default='1', max_length=25, verbose_name='type deadline')),
                ('name', models.CharField(max_length=450, verbose_name='name')),
                ('comment', models.CharField(blank=True, max_length=1500, null=True, verbose_name='comment')),
                ('receptor_blood_type', models.CharField(choices=[('o-', 'O-'), ('o+', 'O+'), ('a-', 'A-'), ('a+', 'A+'), ('b-', 'B-'), ('b+', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB-')], default='o+', max_length=4, verbose_name='receptor blood type')),
                ('unit_type', models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='unit type')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('destination', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blood_center.center', verbose_name='destination')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blood_center.center', verbose_name='origin')),
            ],
            options={
                'verbose_name': 'historical center transfer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCenterCapacity',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='blood unit type')),
                ('min_qty', models.PositiveIntegerField(verbose_name='minimum quantity')),
                ('max_qty', models.PositiveIntegerField(verbose_name='maximum quantity')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blood_center.center', verbose_name='center')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical center capacity',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCenter',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=18, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=18, verbose_name='longitude')),
                ('type', models.CharField(choices=[('imss', 'IMSS'), ('issste', 'ISSSTE'), ('cnts', 'CNTS (Centro Nacional de la Transfusión Sanguínea)'), ('cets', 'CETS (Centro Estatal de la Transfusión Sanguínea)'), ('ccinshae', 'CCINSHAE (Comisión Coordinadora de Institutos Nacionales de Salud y Hospitales de Alta Especialidad)'), ('dif', 'DIF'), ('pemex', 'PEMEX'), ('sedena', 'SEDENA'), ('semar', 'SEMAR'), ('privados', 'PRIVADOS'), ('universitarios', 'UNIVERSITARIOS'), ('cruz_roja', 'CRUZ_ROJA')], default='imss', max_length=150, verbose_name='type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical center',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
