# Generated by Django 3.2 on 2022-04-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0011_historicalcenter_historicalcentercapacity_historicalcentertransfer_historicalcentertransferunit_hist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'Center', 'verbose_name_plural': 'Centers'},
        ),
        migrations.AlterModelOptions(
            name='centercapacity',
            options={'verbose_name': 'Center Capacity', 'verbose_name_plural': 'Centers Capacity'},
        ),
        migrations.AlterModelOptions(
            name='centertransfer',
            options={'verbose_name': 'Center Transfer', 'verbose_name_plural': 'Centers Transfers'},
        ),
        migrations.AlterModelOptions(
            name='centertransferunit',
            options={'verbose_name': 'Center Transfer Unit', 'verbose_name_plural': 'Center Transfer Units'},
        ),
        migrations.AlterModelOptions(
            name='historicalcenter',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Center'},
        ),
        migrations.AlterModelOptions(
            name='historicalcentercapacity',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Center Capacity'},
        ),
        migrations.AlterModelOptions(
            name='historicalcentertransfer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Center Transfer'},
        ),
        migrations.AlterModelOptions(
            name='historicalcentertransferunit',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Center Transfer Unit'},
        ),
        migrations.AlterModelOptions(
            name='historicalunit',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Unit'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterUniqueTogether(
            name='centertransferunit',
            unique_together={('transfer', 'unit')},
        ),
        migrations.AlterModelTable(
            name='center',
            table='center',
        ),
        migrations.AlterModelTable(
            name='centercapacity',
            table='center_capacity',
        ),
        migrations.AlterModelTable(
            name='centertransfer',
            table='center_transfer',
        ),
        migrations.AlterModelTable(
            name='centertransferunit',
            table='center_transfer_unit',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='unit',
        ),
    ]
