# Generated by Django 3.2 on 2022-04-25 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0013_auto_20220424_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centertransferunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='blood_center.unit', verbose_name='unit'),
        ),
    ]
