# Generated by Django 3.2 on 2022-04-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0014_alter_centertransferunit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centertransfer',
            name='receptor_blood_type',
            field=models.CharField(choices=[('o-', 'O-'), ('o+', 'O+'), ('a-', 'A-'), ('a+', 'A+'), ('b-', 'B-'), ('b+', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB+')], default='o+', max_length=4, verbose_name='receptor blood type'),
        ),
        migrations.AlterField(
            model_name='historicalcentertransfer',
            name='receptor_blood_type',
            field=models.CharField(choices=[('o-', 'O-'), ('o+', 'O+'), ('a-', 'A-'), ('a+', 'A+'), ('b-', 'B-'), ('b+', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB+')], default='o+', max_length=4, verbose_name='receptor blood type'),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='blood_type',
            field=models.CharField(choices=[('o-', 'O-'), ('o+', 'O+'), ('a-', 'A-'), ('a+', 'A+'), ('b-', 'B-'), ('b+', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB+')], default='o+', max_length=4, verbose_name='blood type'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='blood_type',
            field=models.CharField(choices=[('o-', 'O-'), ('o+', 'O+'), ('a-', 'A-'), ('a+', 'A+'), ('b-', 'B-'), ('b+', 'B+'), ('ab-', 'AB-'), ('ab+', 'AB+')], default='o+', max_length=4, verbose_name='blood type'),
        ),
    ]
