# Generated by Django 3.2 on 2022-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0015_auto_20220426_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centertransfer',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('created', 'Created'), ('confirmed', 'Confirmed'), ('prepared', 'Prepared'), ('sending', 'Sending'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('verifying', 'Verifying'), ('finished', 'Finished')], default='created', max_length=25, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalcentertransfer',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('created', 'Created'), ('confirmed', 'Confirmed'), ('prepared', 'Prepared'), ('sending', 'Sending'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('verifying', 'Verifying'), ('finished', 'Finished')], default='created', max_length=25, verbose_name='status'),
        ),
        migrations.AlterModelTable(
            name='historicalcenter',
            table='center_history',
        ),
        migrations.AlterModelTable(
            name='historicalcentercapacity',
            table='center_capacity_history',
        ),
        migrations.AlterModelTable(
            name='historicalcentertransfer',
            table='center_transfer_history',
        ),
        migrations.AlterModelTable(
            name='historicalcentertransferunit',
            table='center_transfer_unit_history',
        ),
        migrations.AlterModelTable(
            name='historicalunit',
            table='unit_history',
        ),
    ]
