# Generated by Django 3.2 on 2022-05-09 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_center', '0016_auto_20220430_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCenterTransferUnitIncident',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.CharField(max_length=500, verbose_name='incident')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blood_center.centertransferunit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'historical Center Transfer Unit Incident',
                'db_table': 'center_transfer_unit_incident_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CenterTransferUnitIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.CharField(max_length=500, verbose_name='incident')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='blood_center.centertransferunit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'Center Transfer Unit Incident',
                'verbose_name_plural': 'Center Transfer Unit Incidents',
                'db_table': 'center_transfer_unit_incident',
            },
        ),
    ]
