# Generated by Django 3.2 on 2022-05-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0017_centertransferunitincident_historicalcentertransferunitincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(decimal_places=18, max_digits=20, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(decimal_places=18, max_digits=20, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='centercapacity',
            name='type',
            field=models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritrorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='blood unit type'),
        ),
        migrations.AlterField(
            model_name='centertransfer',
            name='unit_type',
            field=models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritrorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='unit type'),
        ),
        migrations.AlterField(
            model_name='historicalcenter',
            name='latitude',
            field=models.DecimalField(decimal_places=18, max_digits=20, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='historicalcenter',
            name='longitude',
            field=models.DecimalField(decimal_places=18, max_digits=20, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='historicalcentercapacity',
            name='type',
            field=models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritrorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='blood unit type'),
        ),
        migrations.AlterField(
            model_name='historicalcentertransfer',
            name='unit_type',
            field=models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritrorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='unit type'),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='type',
            field=models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritrorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('ST', 'ST (Sangre total)'), ('CE', 'CE (Concentrado de eritrorcitos)'), ('CP', 'CP (Concentrado de plaquetas)'), ('PF', 'PF (Plasma fresco)'), ('PDFL', 'PDFL (Plasma desprovisto de factores lábiles)'), ('CRIO', 'CRIO (Crioprecipitado)')], default='ST', max_length=55, verbose_name='type'),
        ),
    ]
