# Generated by Django 3.2 on 2022-05-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_center', '0018_auto_20220529_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(decimal_places=18, max_digits=21, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(decimal_places=18, max_digits=21, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='historicalcenter',
            name='latitude',
            field=models.DecimalField(decimal_places=18, max_digits=21, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='historicalcenter',
            name='longitude',
            field=models.DecimalField(decimal_places=18, max_digits=21, verbose_name='longitude'),
        ),
    ]
