name: blood_bank
description: A new Flutter project.

publish_to: 'Adrian Gonzalez Pardo'

version: 1.0.1+1

environment:
  sdk: '>=2.18.0-115.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.6
  email_validator: ^2.0.1
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_dotenv: ^5.0.2
  google_fonts: ^2.3.2
  localization: ^2.1.0
  mdi: ^5.0.0-nullsafety.0
  provider: ^6.0.2
  select_form_field: ^2.2.0
  shared_preferences: ^2.0.15
  timezone: ^0.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/login_1.jpg
    - .env
